In [2]:
import pandas as pd

In [7]:
CCTV_seoul = pd.read_csv("../../Data/CCTV_in_Seoul.csv", encoding = 'utf-8') #현재위치 기준으로 나왔다 들어갔다를 고려해야 한다

In [8]:
CCTV_seoul.head()

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  3238       1292    430    584    932
1  강동구  1010        379     99    155    377
2  강북구   831        369    120    138    204
3  강서구   911        388    258    184     81
4  관악구  2109        846    260    390    613

In [9]:
CCTV_seoul.columns

Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

In [10]:
CCTV_seoul.rename(columns={CCTV_seoul.columns[0]:'구별'}, inplace=True) #coulumn 이름 바꾸어 주기 -->rename

In [11]:
CCTV_seoul.head()

    구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  3238       1292    430    584    932
1  강동구  1010        379     99    155    377
2  강북구   831        369    120    138    204
3  강서구   911        388    258    184     81
4  관악구  2109        846    260    390    613

In [22]:
pop_seoul = pd.read_excel('../../Data/pop_in_seoul.xls', 
                          header = 2,
                          usecols = 'B, D, G, J, N',
                          encoding='utf-8') # 엑셀의 셀 이름별로 자기가 원하는 데이터를 선별적으로 가져올 수 있다. 헤더는 몇번째 행부터 가져올지(가로)

In [23]:
pop_seoul.head()

   자치구           계        계.1       계.2   65세이상고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [25]:
CCTV_seoul.sort_values(by = '소계').head() #--> 소계 기준 오름차순으로 / ascending = False 넣어야 내림차순

     구별   소계  2013년도 이전  2014년  2015년  2016년
9   도봉구  825        238    159     42    386
2   강북구  831        369    120    138    204
5   광진구  878        573     78     53    174
3   강서구  911        388    258    184     81
24  중랑구  916        509    121    177    109

In [26]:
pop_seoul.rename(columns={pop_seoul.columns[0]:'구별',
                          pop_seoul.columns[1]:'인구수',
                          pop_seoul.columns[2]:'한국인',
                          pop_seoul.columns[3]:'외국인',
                          pop_seoul.columns[4]:'고령자',
                         } , inplace = True)

In [27]:
pop_seoul.head()

    구별         인구수        한국인       외국인        고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [29]:
pop_seoul.drop([0] , inplace =True) # 행 지우기

In [30]:
pop_seoul.head()

    구별       인구수       한국인      외국인      고령자
1  종로구  162820.0  153589.0   9231.0  25425.0
2   중구  133240.0  124312.0   8928.0  20764.0
3  용산구  244203.0  229456.0  14747.0  36231.0
4  성동구  311244.0  303380.0   7864.0  39997.0
5  광진구  372164.0  357211.0  14953.0  42214.0

In [33]:
pop_seoul['구별'].unique() # 중복 검사

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구', nan],
      dtype=object)

In [34]:
pop_seoul['구별'].isnull() # null 값이 있는지 체크

1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
Name: 구별, dtype: bool

In [35]:
pop_seoul[pop_seoul['구별'].isnull()]

     구별  인구수  한국인  외국인  고령자
26  NaN  NaN  NaN  NaN  NaN

In [36]:
pop_seoul.drop([26] , inplace =True)

In [37]:
pop_seoul

      구별       인구수       한국인      외국인      고령자
1    종로구  162820.0  153589.0   9231.0  25425.0
2     중구  133240.0  124312.0   8928.0  20764.0
3    용산구  244203.0  229456.0  14747.0  36231.0
4    성동구  311244.0  303380.0   7864.0  39997.0
5    광진구  372164.0  357211.0  14953.0  42214.0
6   동대문구  369496.0  354079.0  15417.0  54173.0
7    중랑구  414503.0  409882.0   4621.0  56774.0
8    성북구  461260.0  449773.0  11487.0  64692.0
9    강북구  330192.0  326686.0   3506.0  54813.0
10   도봉구  348646.0  346629.0   2017.0  51312.0
11   노원구  569384.0  565565.0   3819.0  71941.0
12   은평구  494388.0  489943.0   4445.0  72334.0
13  서대문구  327163.0  314982.0  12181.0  48161.0
14   마포구  389649.0  378566.0  11083.0  48765.0
15   양천구  479978.0  475949.0   4029.0  52975.0
16   강서구  603772.0  597248.0   6524.0  72548.0
17   구로구  447874.0  416487.0  31387.0  56833.0
18   금천구  255082.0  236353.0  18729.0  32970.0
19  영등포구  402985.0  368072.0  34913.0  52413.0
20   동작구  412520.0  400456.0  12064.0  56013.0
21   관악구  525515.0  507203.0  18312.0  68082.0
22   서초구  450310.0  445994.0   4316.0  51733.0
23   강남구  570500.0  565550.0   4950.0  63167.0
24   송파구  667483.0  660584.0   6899.0  72506.0
25   강동구  453233.0  449019.0   4214.0  54622.0

In [38]:
pop_seoul['외국인 비율'] = pop_seoul['외국인']/pop_seoul['인구수'] *100 # 파생변수 만들어서 넣기

In [39]:
pop_seoul

      구별       인구수       한국인      외국인      고령자    외국인 비율
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828
4    성동구  311244.0  303380.0   7864.0  39997.0  2.526635
5    광진구  372164.0  357211.0  14953.0  42214.0  4.017852
6   동대문구  369496.0  354079.0  15417.0  54173.0  4.172440
7    중랑구  414503.0  409882.0   4621.0  56774.0  1.114829
8    성북구  461260.0  449773.0  11487.0  64692.0  2.490353
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806
10   도봉구  348646.0  346629.0   2017.0  51312.0  0.578524
11   노원구  569384.0  565565.0   3819.0  71941.0  0.670725
12   은평구  494388.0  489943.0   4445.0  72334.0  0.899091
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221
14   마포구  389649.0  378566.0  11083.0  48765.0  2.844355
15   양천구  479978.0  475949.0   4029.0  52975.0  0.839413
16   강서구  603772.0  597248.0   6524.0  72548.0  1.080540
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598
20   동작구  412520.0  400456.0  12064.0  56013.0  2.924464
21   관악구  525515.0  507203.0  18312.0  68082.0  3.484582
22   서초구  450310.0  445994.0   4316.0  51733.0  0.958451
23   강남구  570500.0  565550.0   4950.0  63167.0  0.867660
24   송파구  667483.0  660584.0   6899.0  72506.0  1.033584
25   강동구  453233.0  449019.0   4214.0  54622.0  0.929765

In [40]:
pop_seoul['고령자 비율'] = pop_seoul['고령자']/pop_seoul['인구수'] *100

In [41]:
pop_seoul

      구별       인구수       한국인      외국인      고령자    외국인 비율     고령자 비율
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
4    성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689
5    광진구  372164.0  357211.0  14953.0  42214.0  4.017852  11.342849
6   동대문구  369496.0  354079.0  15417.0  54173.0  4.172440  14.661322
7    중랑구  414503.0  409882.0   4621.0  56774.0  1.114829  13.696885
8    성북구  461260.0  449773.0  11487.0  64692.0  2.490353  14.025062
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806  16.600342
10   도봉구  348646.0  346629.0   2017.0  51312.0  0.578524  14.717507
11   노원구  569384.0  565565.0   3819.0  71941.0  0.670725  12.634883
12   은평구  494388.0  489943.0   4445.0  72334.0  0.899091  14.631019
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221  14.720797
14   마포구  389649.0  378566.0  11083.0  48765.0  2.844355  12.515110
15   양천구  479978.0  475949.0   4029.0  52975.0  0.839413  11.036964
16   강서구  603772.0  597248.0   6524.0  72548.0  1.080540  12.015794
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998  12.689506
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345  12.925255
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598  13.006191
20   동작구  412520.0  400456.0  12064.0  56013.0  2.924464  13.578251
21   관악구  525515.0  507203.0  18312.0  68082.0  3.484582  12.955291
22   서초구  450310.0  445994.0   4316.0  51733.0  0.958451  11.488308
23   강남구  570500.0  565550.0   4950.0  63167.0  0.867660  11.072217
24   송파구  667483.0  660584.0   6899.0  72506.0  1.033584  10.862599
25   강동구  453233.0  449019.0   4214.0  54622.0  0.929765  12.051638

In [42]:
pop_seoul.sort_values(by = '인구수').head() # 인구수로 오름차순 하기

     구별       인구수       한국인      외국인      고령자    외국인 비율     고령자 비율
2    중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909
1   종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
3   용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
18  금천구  255082.0  236353.0  18729.0  32970.0  7.342345  12.925255
4   성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689

In [47]:
pop_seoul.sort_values(by = '인구수', ascending = False) # 인구수로 내림차순 하기

      구별       인구수       한국인      외국인      고령자    외국인 비율     고령자 비율
24   송파구  667483.0  660584.0   6899.0  72506.0  1.033584  10.862599
16   강서구  603772.0  597248.0   6524.0  72548.0  1.080540  12.015794
23   강남구  570500.0  565550.0   4950.0  63167.0  0.867660  11.072217
11   노원구  569384.0  565565.0   3819.0  71941.0  0.670725  12.634883
21   관악구  525515.0  507203.0  18312.0  68082.0  3.484582  12.955291
12   은평구  494388.0  489943.0   4445.0  72334.0  0.899091  14.631019
15   양천구  479978.0  475949.0   4029.0  52975.0  0.839413  11.036964
8    성북구  461260.0  449773.0  11487.0  64692.0  2.490353  14.025062
25   강동구  453233.0  449019.0   4214.0  54622.0  0.929765  12.051638
22   서초구  450310.0  445994.0   4316.0  51733.0  0.958451  11.488308
17   구로구  447874.0  416487.0  31387.0  56833.0  7.007998  12.689506
7    중랑구  414503.0  409882.0   4621.0  56774.0  1.114829  13.696885
20   동작구  412520.0  400456.0  12064.0  56013.0  2.924464  13.578251
19  영등포구  402985.0  368072.0  34913.0  52413.0  8.663598  13.006191
14   마포구  389649.0  378566.0  11083.0  48765.0  2.844355  12.515110
5    광진구  372164.0  357211.0  14953.0  42214.0  4.017852  11.342849
6   동대문구  369496.0  354079.0  15417.0  54173.0  4.172440  14.661322
10   도봉구  348646.0  346629.0   2017.0  51312.0  0.578524  14.717507
9    강북구  330192.0  326686.0   3506.0  54813.0  1.061806  16.600342
13  서대문구  327163.0  314982.0  12181.0  48161.0  3.723221  14.720797
4    성동구  311244.0  303380.0   7864.0  39997.0  2.526635  12.850689
18   금천구  255082.0  236353.0  18729.0  32970.0  7.342345  12.925255
3    용산구  244203.0  229456.0  14747.0  36231.0  6.038828  14.836427
1    종로구  162820.0  153589.0   9231.0  25425.0  5.669451  15.615404
2     중구  133240.0  124312.0   8928.0  20764.0  6.700690  15.583909

In [51]:
CCTV_seoul['최근증가율'] = (CCTV_seoul['2016년']+CCTV_seoul['2015년']+CCTV_seoul['2015년'])/CCTV_seoul['2013년도 이전']*100

In [52]:
CCTV_seoul

      구별    소계  2013년도 이전  2014년  2015년  2016년       최근증가율
0    강남구  3238       1292    430    584    932  162.538700
1    강동구  1010        379     99    155    377  181.266491
2    강북구   831        369    120    138    204  130.081301
3    강서구   911        388    258    184     81  115.721649
4    관악구  2109        846    260    390    613  164.657210
5    광진구   878        573     78     53    174   48.865620
6    구로구  1884       1142    173    246    323   71.366025
7    금천구  1348        674     51    269    354  132.344214
8    노원구  1566        542     57    451    516  261.623616
9    도봉구   825        238    159     42    386  197.478992
10  동대문구  1870       1070     23    198    579   91.121495
11   동작구  1302        544    341    103    314   95.588235
12   마포구   980        314    118    169    379  228.343949
13  서대문구  1254        844     50     68    292   50.710900
14   서초구  2297       1406    157    336    398   76.102418
15   성동구  1327        730     91    241    265  102.328767
16   성북구  1651       1009     78    360    204   91.575818
17   송파구  1081        529     21     68    463  113.232514
18   양천구  2482       1843    142     30    467   28.594683
19  영등포구  1277        495    214    195    373  154.141414
20   용산구  2096       1368    218    112    398   45.467836
21   은평구  2108       1138    224    278    468   89.982425
22   종로구  1619        464    314    211    630  226.724138
23    중구  1023        413    190     72    348  119.128329
24   중랑구   916        509    121    177    109   90.962672

In [53]:
# dataframe 합칠때 merge 함수를 사용한다. pandas 내에 있다/.

In [54]:
data_rewsult =pd.merge(CCTV_seoul , pop_seoul, on = '구별') # 공통된 부분을 기준으로 붙인다

In [55]:
data_rewsult

,구별,소계,2013년도 이전,2014년,2015년,2016년,최근증가율,인구수,한국인,외국인,고령자,외국인 비율,고령자 비율
0,강남구,3238,1292,430,584,932,162.538700,570500.0,565550.0,4950.0,63167.0,0.867660,11.072217
1,강동구,1010,379,99,155,377,181.266491,453233.0,449019.0,4214.0,54622.0,0.929765,12.051638
2,강북구,831,369,120,138,204,130.081301,330192.0,326686.0,3506.0,54813.0,1.061806,16.600342
3,강서구,911,388,258,184,81,115.721649,603772.0,597248.0,6524.0,72548.0,1.080540,12.015794
4,관악구,2109,846,260,390,613,164.657210,525515.0,507203.0,18312.0,68082.0,3.484582,12.955291
5,광진구,878,573,78,53,174,48.865620,372164.0,357211.0,14953.0,42214.0,4.017852,11.342849
6,구로구,1884,1142,173,246,323,71.366025,447874.0,416487.0,31387.0,56833.0,7.007998,12.689506
7,금천구,1348,674,51,269,354,132.344214,255082.0,236353.0,18729.0,32970.0,7.342345,12.925255
8,노원구,1566,542,57,451,516,261.623616,569384.0,565565.0,3819.0,71941.0,0.670725,12.634883
9,도봉구,825,238,159,42,386,197.478992,348646.0,346629.0,2017.0,51312.0,0.578524,14.717507
10,동대문구,1870,1070,23,198,579,91.121495,369496.0,354079.0,15417.0,54173.0,4.172440,14.661322
11,동작구,1302,544,341,103,314,95.588235,412520.0,400456.0,12064.0,56013.0,2.924464,13.578251
12,마포구,980,314,118,169,379,228.343949,389649.0,378566.0,11083.0,48765.0,2.844355,12.515110
13,서대문구,1254,844,50,68,292,50.710900,327163.0,314982.0,12181.0,48161.0,3.723221,14.720797
14,서초구,2297,1406,157,336,398,76.102418,450310.0,445994.0,4316.0,51733.0,0.958451,11.488308
15,성동구,1327,730,91,241,265,102.328767,311244.0,303380.0,7864.0,39997.0,2.526635,12.850689
16,성북구,1651,1009,78,360,204,91.575818,461260.0,449773.0,11487.0,64692.0,2.490353,14.025062
17,송파구,1081,529,21,68,463,113.232514,667483.0,660584.0,6899.0,72506.0,1.033584,10.862599
18,양천구,2482,1843,142,30,467,28.594683,479978.0,475949.0,4029.0,52975.0,0.839413,11.036964
19,영등포구,1277,495,214,195,373,154.141414,402985.0,368072.0,34913.0,52413.0,8.663598,13.006191
20,용산구,2096,1368,218,112,398,45.467836,244203.0,229456.0,14747.0,36231.0,6.038828,14.836427
21,은평구,2108,1138,224,278,468,89.982425,494388.0,489943.0,4445.0,72334.0,0.899091,14.631019
22,종로구,1619,464,314,211,630,226.724138,162820.0,153589.0,9231.0,25425.0,5.669451,15.615404
23,중구,1023,413,190,72,348,119.128329,133240.0,124312.0,8928.0,20764.0,6.700690,15.583909
24,중랑구,916,509,121,177,109,90.962672,414503.0,409882.0,4621.0,56774.0,1.114829,13.696885

In [56]:
del data_rewsult['2013년도 이전']#열을 지워보자
del data_rewsult['2014년']
del data_rewsult['2015년']
del data_rewsult['2016년']
# 데이터 프레임의 컬럼 삭제 del
data_rewsult

,구별,소계,최근증가율,인구수,한국인,외국인,고령자,외국인 비율,고령자 비율
0,강남구,3238,162.538700,570500.0,565550.0,4950.0,63167.0,0.867660,11.072217
1,강동구,1010,181.266491,453233.0,449019.0,4214.0,54622.0,0.929765,12.051638
2,강북구,831,130.081301,330192.0,326686.0,3506.0,54813.0,1.061806,16.600342
3,강서구,911,115.721649,603772.0,597248.0,6524.0,72548.0,1.080540,12.015794
4,관악구,2109,164.657210,525515.0,507203.0,18312.0,68082.0,3.484582,12.955291
5,광진구,878,48.865620,372164.0,357211.0,14953.0,42214.0,4.017852,11.342849
6,구로구,1884,71.366025,447874.0,416487.0,31387.0,56833.0,7.007998,12.689506
7,금천구,1348,132.344214,255082.0,236353.0,18729.0,32970.0,7.342345,12.925255
8,노원구,1566,261.623616,569384.0,565565.0,3819.0,71941.0,0.670725,12.634883
9,도봉구,825,197.478992,348646.0,346629.0,2017.0,51312.0,0.578524,14.717507
10,동대문구,1870,91.121495,369496.0,354079.0,15417.0,54173.0,4.172440,14.661322
11,동작구,1302,95.588235,412520.0,400456.0,12064.0,56013.0,2.924464,13.578251
12,마포구,980,228.343949,389649.0,378566.0,11083.0,48765.0,2.844355,12.515110
13,서대문구,1254,50.710900,327163.0,314982.0,12181.0,48161.0,3.723221,14.720797
14,서초구,2297,76.102418,450310.0,445994.0,4316.0,51733.0,0.958451,11.488308
15,성동구,1327,102.328767,311244.0,303380.0,7864.0,39997.0,2.526635,12.850689
16,성북구,1651,91.575818,461260.0,449773.0,11487.0,64692.0,2.490353,14.025062
17,송파구,1081,113.232514,667483.0,660584.0,6899.0,72506.0,1.033584,10.862599
18,양천구,2482,28.594683,479978.0,475949.0,4029.0,52975.0,0.839413,11.036964
19,영등포구,1277,154.141414,402985.0,368072.0,34913.0,52413.0,8.663598,13.006191
20,용산구,2096,45.467836,244203.0,229456.0,14747.0,36231.0,6.038828,14.836427
21,은평구,2108,89.982425,494388.0,489943.0,4445.0,72334.0,0.899091,14.631019
22,종로구,1619,226.724138,162820.0,153589.0,9231.0,25425.0,5.669451,15.615404
23,중구,1023,119.128329,133240.0,124312.0,8928.0,20764.0,6.700690,15.583909
24,중랑구,916,90.962672,414503.0,409882.0,4621.0,56774.0,1.114829,13.696885

In [57]:
data_rewsult.set_index('구별', inplace = True) #구별로 구분해서 인덱싱

In [58]:
data_rewsult

,소계,최근증가율,인구수,한국인,외국인,고령자,외국인 비율,고령자 비율
구별,,,,,,,,
강남구,3238,162.538700,570500.0,565550.0,4950.0,63167.0,0.867660,11.072217
강동구,1010,181.266491,453233.0,449019.0,4214.0,54622.0,0.929765,12.051638
강북구,831,130.081301,330192.0,326686.0,3506.0,54813.0,1.061806,16.600342
강서구,911,115.721649,603772.0,597248.0,6524.0,72548.0,1.080540,12.015794
관악구,2109,164.657210,525515.0,507203.0,18312.0,68082.0,3.484582,12.955291
광진구,878,48.865620,372164.0,357211.0,14953.0,42214.0,4.017852,11.342849
구로구,1884,71.366025,447874.0,416487.0,31387.0,56833.0,7.007998,12.689506
금천구,1348,132.344214,255082.0,236353.0,18729.0,32970.0,7.342345,12.925255
노원구,1566,261.623616,569384.0,565565.0,3819.0,71941.0,0.670725,12.634883
도봉구,825,197.478992,348646.0,346629.0,2017.0,51312.0,0.578524,14.717507
동대문구,1870,91.121495,369496.0,354079.0,15417.0,54173.0,4.172440,14.661322
동작구,1302,95.588235,412520.0,400456.0,12064.0,56013.0,2.924464,13.578251
마포구,980,228.343949,389649.0,378566.0,11083.0,48765.0,2.844355,12.515110
서대문구,1254,50.710900,327163.0,314982.0,12181.0,48161.0,3.723221,14.720797
서초구,2297,76.102418,450310.0,445994.0,4316.0,51733.0,0.958451,11.488308
성동구,1327,102.328767,311244.0,303380.0,7864.0,39997.0,2.526635,12.850689
성북구,1651,91.575818,461260.0,449773.0,11487.0,64692.0,2.490353,14.025062
송파구,1081,113.232514,667483.0,660584.0,6899.0,72506.0,1.033584,10.862599
양천구,2482,28.594683,479978.0,475949.0,4029.0,52975.0,0.839413,11.036964
영등포구,1277,154.141414,402985.0,368072.0,34913.0,52413.0,8.663598,13.006191
용산구,2096,45.467836,244203.0,229456.0,14747.0,36231.0,6.038828,14.836427
은평구,2108,89.982425,494388.0,489943.0,4445.0,72334.0,0.899091,14.631019
종로구,1619,226.724138,162820.0,153589.0,9231.0,25425.0,5.669451,15.615404
중구,1023,119.128329,133240.0,124312.0,8928.0,20764.0,6.700690,15.583909
중랑구,916,90.962672,414503.0,409882.0,4621.0,56774.0,1.114829,13.696885

In [59]:
import numpy as np

In [60]:
np.corrcoef(data_rewsult['고령자 비율'] , data_rewsult['소계']) #상관도 분석

array([[ 1.        , -0.25866272],
       [-0.25866272,  1.        ]])

In [61]:
np.corrcoef(data_rewsult['외국인 비율'] , data_rewsult['소계'])

array([[ 1.        , -0.05230165],
       [-0.05230165,  1.        ]])

In [62]:
np.corrcoef(data_rewsult['인구수'] , data_rewsult['소계'])

array([[1.       , 0.2432198],
       [0.2432198, 1.       ]])

In [69]:
import matplotlib as plt # 시각화 라이브러리 /# 그래프가 라인 하나를 차지하도록 (보고서용)
%matplotlib inline

In [70]:
import platform # 내 Pc에 있는 데이터를 이용 가능하게 해주는 라이브러리

In [71]:
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~')
    
### matplotlib 한국어 입력가능하게 해주는 기능. 그대로 쓰면 된다

In [74]:
plt.figure() #그림 그리는 툴을 만들어 준다
data_rewsult['소계'].plot(kind = 'barh', grid = True , figsize = (10,10)) # 막대그래프 뒤는 그냥 옵션
#                             그래프종류      격자무늬     사이즈

TypeError: 'module' object is not callable

In [ ]:
plt.show()